#!/usr/bin/env bash
# This script is displaying "Best School" 10 times with while in 9 say hi.
n=0
while [ $n -le 9 ]
do
    if [ $n -eq 8 ]
       then
       echo -e  "Best School\nHi"
	else   
    echo "Best School"
    fi
    (( n=n+1 ))
   done
