#!/usr/bin/env bash
# This script is displaying "Best School" repeat 10 times in for bad luck 8 is your chance.
n=0
while [ $n -le 9 ]
do
    if [ $n -eq 3 ]
       then
	   echo -e  "Bad luck"
    elif [ $n -eq 7 ]
    then
	echo -e "good luck"
	else   
    echo "Best School"
    fi
    (( n=n+1 ))
   done
