#!/usr/bin/env bash
# This script is displaying "Best School" repeat 10 times in for bad luck 8 is your chance.
n=1
while [ $n -le 20 ]
do
    echo "$Counter"
    case "$Counter" in
4)
    echo "bad luck from China"
    ;;
9)
    echo "bad luck from Japan"
    ;;
17)
    echo "bad luck from Italy"
    ;;
    esac
    (( n++ ))
   done
