#!/usr/bin/env bash
#  Script bash that displays  gives you information about the school file.
school=$1
if [ -e school ]
then
    echo "school file exists"
    if [ -s school ]
    then
echo "school file is not empty"
    else
echo "school file is empty"
    fi
    if [ -f school ]
    then
echo "school is a regular file"
    else
	fi
    echo "school file does not exist"
fi
