#!/usr/bin/env bash
# write Bash (init) script 11-manage_my_process that manages manage_my_process.

echo "$$" > /var/run/myscript.pid
while :
do
    echo "To infinity and beyond"
trap "echo 'Y U no love me?!'" SIGINT
trap "echo 'I hate the kill command';  rm /var/run/myscript.pid; exit" SIGTERM
trap " /var/run/myscript.pid; exit" SIGQUIT
done
