#!/usr/bin/env bash
# write Bash (init) script 11-manage_my_process that manages manage_my_process.
if [ "$aa" = "start" ]
then
    ./manage_my_process &
    echo $$ > /var/run/my_process.pid
    echo "manage_my_process started"
elif [ "$aa" = "stop" ]
then
    pkill -f ./manage_my_process
    sudo rm /var/run/my_process.pid
    echo "manage_my_process stopped"
elif [ "$aa" = "restart" ]
then
    pkill -f ./manage_my_process
    sudo rm /var/run/my_process.pid
    ./manage_my_process &
    echo $$ > /var/run/my_process.pid
    echo "manage_my_process restarted"
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
